<!--<div class="pagination" style="width:100%">  -->
<!-- <div style="float:left;width:28%"> -->
<?php if($this->last > 1) {?>
<table class="pagination">
	<tr>
	<td class="paginatorsummary">	
		Showing page <?= $this->current ?> of <?= $this->last ?>
    </td>
    <td class="paginator">
		
    	<!-- First page link -->
  
    	<?php if (isset($this->previous)) { ?>

     	 	<a href="<?= $this->url(array('page' => $this->first)); ?>">Start</a> 

    	<?php } ?>

    <!-- Previous page link -->

	    <?php if (isset($this->previous)) { ?>

    		  <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a> 

    	<?php } ?>

    <!-- Numbered page links -->

    	<?php foreach ($this->pagesInRange as $page){ ?>

   			<?php if ($page != $this->current){ ?>

        		<a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>

    		<?php }else{ ?>

			    <?= $page; ?>

    		<?php } ?>

	    <?php } ?>

    <!-- Next page link -->

	    <?php if (isset($this->next)){ ?>

    		   <a href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a> 

	    <?php } ?>

    <!-- Last page link -->

    	<?php if (isset($this->next)){ ?>

     		 <a href="<?= $this->url(array('page' => $this->last)); ?>">End</a>


	    <?php } ?>

<?php }
elseif($this->currentItemCount == 0) 
{
	echo 'No result.';	
}?>
    	</td>
	</tr>
</table>
