<?php echo $this->form->getSearchResults($this->category, $this->paramsHolder->cat1, $this->paramsHolder->cat2, $this->paramsHolder->cat3, $this->paramsHolder->cat4, $this->paramsHolder->cat5);?>
<div class="formandresultlistwrap">
	<div class="refineformwrap">
		<?php echo $this->form->populate(Common::stdClassToArray($this->paramsHolder));?>
	</div>
	<div class="resultlistwrap">
		<div class="resultwrap">
			<div class="resultsummary">
					Showing <?=$this->currentItemCount?> of <?=$this->itemCount?>
			</div>
			<div class="resultcontent"> 
				<?php $this->business->getResultTable($this->postings, $this->location)?>
			</div>			
		</div>
		

		<div class="botbar">
			<div class="centercolumn botcenter">
				<center>
					<?php echo $this->postings ;?>
				</center>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>