<option value="Aus41" <?php if ($this->locationId == "Aus41") echo '"selected="selected"'; ?>>Brisbane Region - Australia</option>

<option value="Aus11" <?php if ($this->locationId == "Aus11") echo '"selected="selected"'; ?>>Canberra - Australia</option>

<option value="Aus42" <?php if ($this->locationId == "Aus42") echo '"selected="selected"'; ?>>Central & Western - Australia</option>

<option value="Aus21" <?php if ($this->locationId == "Aus21") echo '"selected="selected"'; ?>>Central Coast - Australia</option>

<option value="Aus43" <?php if ($this->locationId == "Aus43") echo '"selected="selected"'; ?>>Central Coastal - Australia</option>

<option value="Aus52" <?php if ($this->locationId == "Aus52") echo '"selected="selected"'; ?>>Far North - Australia</option>

<option value="Aus71" <?php if ($this->locationId == "Aus71") echo '"selected="selected"'; ?>>Greater Bendigo Region - Australia</option>

<option value="Aus22" <?php if ($this->locationId == "Aus22") echo '"selected="selected"'; ?>>Hunter Valley - Australia</option>

<option value="Aus23" <?php if ($this->locationId == "Aus23") echo '"selected="selected"'; ?>>Lake Macquarie - Australia</option>

<option value="Aus72" <?php if ($this->locationId == "Aus72") echo '"selected="selected"'; ?>>Macedon Ranges - Australia</option>

<option value="Aus73" <?php if ($this->locationId == "Aus73") echo '"selected="selected"'; ?>>Melbourne - Australia</option>

<option value="Aus53" <?php if ($this->locationId == "Aus53") echo '"selected="selected"'; ?>>Mid North - Australia</option>

<option value="Aus24" <?php if ($this->locationId == "Aus24") echo '"selected="selected"'; ?>>Newcastle - Australia</option>

<option value="Aus74" <?php if ($this->locationId == "Aus74") echo '"selected="selected"'; ?>>North Eastern - Australia</option>

<option value="Aus75" <?php if ($this->locationId == "Aus75") echo '"selected="selected"'; ?>>North Western - Australia</option>

<option value="Aus44" <?php if ($this->locationId == "Aus44") echo '"selected="selected"'; ?>>Northern - Australia</option>

<option value="Aus31" <?php if ($this->locationId == "Aus31") echo '"selected="selected"'; ?>>Northern Territory - Australia</option>

<option value="Aus81" <?php if ($this->locationId == "Aus81") echo '"selected="selected"'; ?>>Northern WA - Australia</option>

<option value="Aus82" <?php if ($this->locationId == "Aus82") echo '"selected="selected"'; ?>>Perth - Australia</option>

<option value="Aus25" <?php if ($this->locationId == "Aus25") echo '"selected="selected"'; ?>>Port Stephens - Australia</option>

<option value="Aus26" <?php if ($this->locationId == "Aus26") echo '"selected="selected"'; ?>>Regional Nsw - Australia</option>

<option value="Aus76" <?php if ($this->locationId == "Aus76") echo '"selected="selected"'; ?>>Shepparton & Central Nort - Australia</option>

<option value="Aus54" <?php if ($this->locationId == "Aus54") echo '"selected="selected"'; ?>>South - Australia</option>

<option value="Aus27" <?php if ($this->locationId == "Aus27") echo '"selected="selected"'; ?>>South Coast - Australia</option>

<option value="Aus83" <?php if ($this->locationId == "Aus83") echo '"selected="selected"'; ?>>South East & Central - Australia</option>

<option value="Aus45" <?php if ($this->locationId == "Aus45") echo '"selected="selected"'; ?>>South Eastern - Australia</option>

<option value="Aus77" <?php if ($this->locationId == "Aus77") echo '"selected="selected"'; ?>>South Eastern Victoria - Australia</option>

<option value="Aus84" <?php if ($this->locationId == "Aus84") echo '"selected="selected"'; ?>>South Western - Australia</option>

<option value="Aus78" <?php if ($this->locationId == "Aus78") echo '"selected="selected"'; ?>>South Western Victoria - Australia</option>

<option value="Aus55" <?php if ($this->locationId == "Aus55") echo '"selected="selected"'; ?>>Spencer Gulf & West Coast - Australia</option>

<option value="Aus28" <?php if ($this->locationId == "Aus28") echo '"selected="selected"'; ?>>Sydney - Australia</option>

<option value="Aus61" <?php if ($this->locationId == "Aus61") echo '"selected="selected"'; ?>>Tasmania - Australia</option>
