<option value="Aus41" <?php if ($this->locationId == "Aus41") echo '"selected="selected"'; ?>>Brisbane Region - Australia</option>

<option value="Aus11" <?php if ($this->locationId == "Aus11") echo '"selected="selected"'; ?>>Canberra - Australia</option>

<option value="Aus42" <?php if ($this->locationId == "Aus42") echo '"selected="selected"'; ?>>Central & Western - Australia</option>

<option value="Aus21" <?php if ($this->locationId == "Aus21") echo '"selected="selected"'; ?>>Central Coast - Australia</option>

<option value="Aus43" <?php if ($this->locationId == "Aus43") echo '"selected="selected"'; ?>>Central Coastal - Australia</option>

<option value="Aus52" <?php if ($this->locationId == "Aus52") echo '"selected="selected"'; ?>>Far North - Australia</option>

<option value="Aus71" <?php if ($this->locationId == "Aus71") echo '"selected="selected"'; ?>>Greater Bendigo Region - Australia</option>

<option value="Aus22" <?php if ($this->locationId == "Aus22") echo '"selected="selected"'; ?>>Hunter Valley - Australia</option>

<option value="Aus23" <?php if ($this->locationId == "Aus23") echo '"selected="selected"'; ?>>Lake Macquarie - Australia</option>

<option value="Aus72" <?php if ($this->locationId == "Aus72") echo '"selected="selected"'; ?>>Macedon Ranges - Australia</option>

<option value="Aus73" <?php if ($this->locationId == "Aus73") echo '"selected="selected"'; ?>>Melbourne - Australia</option>

<option value="Aus53" <?php if ($this->locationId == "Aus53") echo '"selected="selected"'; ?>>Mid North - Australia</option>

<option value="Aus24" <?php if ($this->locationId == "Aus24") echo '"selected="selected"'; ?>>Newcastle - Australia</option>

<option value="Aus74" <?php if ($this->locationId == "Aus74") echo '"selected="selected"'; ?>>North Eastern - Australia</option>

<option value="Aus75" <?php if ($this->locationId == "Aus75") echo '"selected="selected"'; ?>>North Western - Australia</option>

<option value="Aus44" <?php if ($this->locationId == "Aus44") echo '"selected="selected"'; ?>>Northern - Australia</option>

<option value="Aus31" <?php if ($this->locationId == "Aus31") echo '"selected="selected"'; ?>>Northern Territory - Australia</option>

<option value="Aus81" <?php if ($this->locationId == "Aus81") echo '"selected="selected"'; ?>>Northern WA - Australia</option>

<option value="Aus82" <?php if ($this->locationId == "Aus82") echo '"selected="selected"'; ?>>Perth - Australia</option>

<option value="Aus25" <?php if ($this->locationId == "Aus25") echo '"selected="selected"'; ?>>Port Stephens - Australia</option>

<option value="Aus26" <?php if ($this->locationId == "Aus26") echo '"selected="selected"'; ?>>Regional Nsw - Australia</option>

<option value="Aus76" <?php if ($this->locationId == "Aus76") echo '"selected="selected"'; ?>>Shepparton & Central Nort - Australia</option>

<option value="Aus54" <?php if ($this->locationId == "Aus54") echo '"selected="selected"'; ?>>South - Australia</option>

<option value="Aus27" <?php if ($this->locationId == "Aus27") echo '"selected="selected"'; ?>>South Coast - Australia</option>

<option value="Aus83" <?php if ($this->locationId == "Aus83") echo '"selected="selected"'; ?>>South East & Central - Australia</option>

<option value="Aus45" <?php if ($this->locationId == "Aus45") echo '"selected="selected"'; ?>>South Eastern - Australia</option>

<option value="Aus77" <?php if ($this->locationId == "Aus77") echo '"selected="selected"'; ?>>South Eastern Victoria - Australia</option>

<option value="Aus84" <?php if ($this->locationId == "Aus84") echo '"selected="selected"'; ?>>South Western - Australia</option>

<option value="Aus78" <?php if ($this->locationId == "Aus78") echo '"selected="selected"'; ?>>South Western Victoria - Australia</option>

<option value="Aus55" <?php if ($this->locationId == "Aus55") echo '"selected="selected"'; ?>>Spencer Gulf & West Coast - Australia</option>

<option value="Aus28" <?php if ($this->locationId == "Aus28") echo '"selected="selected"'; ?>>Sydney - Australia</option>

<option value="Aus61" <?php if ($this->locationId == "Aus61") echo '"selected="selected"'; ?>>Tasmania - Australia</option>

<option value="Can16" <?php if ($this->locationId == "Can16") echo '"selected="selected"'; ?>>Brampton - Canada</option>

<option value="Can11" <?php if ($this->locationId == "Can11") echo '"selected="selected"'; ?>>Calgary - Canada</option>

<option value="Can17" <?php if ($this->locationId == "Can17") echo '"selected="selected"'; ?>>City Of Toronto - Canada</option>

<option value="Can18" <?php if ($this->locationId == "Can18") echo '"selected="selected"'; ?>>Durham Region - Canada</option>

<option value="Can12" <?php if ($this->locationId == "Can12") echo '"selected="selected"'; ?>>Edmonton - Canada</option>

<option value="Can13" <?php if ($this->locationId == "Can13") echo '"selected="selected"'; ?>>Halifax - Canada</option>

<option value="Can19" <?php if ($this->locationId == "Can19") echo '"selected="selected"'; ?>>Mississauga - Canada</option>

<option value="Can14" <?php if ($this->locationId == "Can14") echo '"selected="selected"'; ?>>Montreal - Canada</option>

<option value="Can20" <?php if ($this->locationId == "Can20") echo '"selected="selected"'; ?>>Oakville - Canada</option>

<option value="Can15" <?php if ($this->locationId == "Can15") echo '"selected="selected"'; ?>>Ottawa - Canada</option>

<option value="Can22" <?php if ($this->locationId == "Can22") echo '"selected="selected"'; ?>>Vancouver - Canada</option>

<option value="Can23" <?php if ($this->locationId == "Can23") echo '"selected="selected"'; ?>>Victoria - Canada</option>

<option value="Can24" <?php if ($this->locationId == "Can24") echo '"selected="selected"'; ?>>Winnipeg - Canada</option>

<option value="Can21" <?php if ($this->locationId == "Can21") echo '"selected="selected"'; ?>>York Region - Canada</option>

<option value="Chi11" <?php if ($this->locationId == "Chi11") echo '"selected="selected"'; ?>>Beijing - China</option>

<option value="Chi12" <?php if ($this->locationId == "Chi12") echo '"selected="selected"'; ?>>Guangzhou - China</option>

<option value="Chi13" <?php if ($this->locationId == "Chi13") echo '"selected="selected"'; ?>>Hangzhou - China</option>

<option value="Chi14" <?php if ($this->locationId == "Chi14") echo '"selected="selected"'; ?>>Hong Kong - China</option>

<option value="Chi15" <?php if ($this->locationId == "Chi15") echo '"selected="selected"'; ?>>Shanghai - China</option>

<option value="Chi16" <?php if ($this->locationId == "Chi16") echo '"selected="selected"'; ?>>Shenzhen - China</option>

<option value="Eng11" <?php if ($this->locationId == "Eng11") echo '"selected="selected"'; ?>>Cental London - England</option>

<option value="Eng12" <?php if ($this->locationId == "Eng12") echo '"selected="selected"'; ?>>East London - England</option>

<option value="Eng13" <?php if ($this->locationId == "Eng13") echo '"selected="selected"'; ?>>North East London - England</option>

<option value="Eng14" <?php if ($this->locationId == "Eng14") echo '"selected="selected"'; ?>>North London - England</option>

<option value="Eng15" <?php if ($this->locationId == "Eng15") echo '"selected="selected"'; ?>>North West London - England</option>

<option value="Eng16" <?php if ($this->locationId == "Eng16") echo '"selected="selected"'; ?>>South East London - England</option>

<option value="Eng17" <?php if ($this->locationId == "Eng17") echo '"selected="selected"'; ?>>South London - England</option>

<option value="Eng18" <?php if ($this->locationId == "Eng18") echo '"selected="selected"'; ?>>South West London - England</option>

<option value="Eng19" <?php if ($this->locationId == "Eng19") echo '"selected="selected"'; ?>>West London - England</option>

<option value="Fra11" <?php if ($this->locationId == "Fra11") echo '"selected="selected"'; ?>>Bordeaux - France</option>

<option value="Fra12" <?php if ($this->locationId == "Fra12") echo '"selected="selected"'; ?>>Brittany - France</option>

<option value="Fra13" <?php if ($this->locationId == "Fra13") echo '"selected="selected"'; ?>>Grenoble - France</option>

<option value="Fra14" <?php if ($this->locationId == "Fra14") echo '"selected="selected"'; ?>>Lille - France</option>

<option value="Fra15" <?php if ($this->locationId == "Fra15") echo '"selected="selected"'; ?>>Loire Valley - France</option>

<option value="Fra16" <?php if ($this->locationId == "Fra16") echo '"selected="selected"'; ?>>Lyon - France</option>

<option value="Fra17" <?php if ($this->locationId == "Fra17") echo '"selected="selected"'; ?>>Marseille - France</option>

<option value="Fra18" <?php if ($this->locationId == "Fra18") echo '"selected="selected"'; ?>>Montpellier - France</option>

<option value="Fra19" <?php if ($this->locationId == "Fra19") echo '"selected="selected"'; ?>>Nice / Cote D'Azur - France</option>

<option value="Fra20" <?php if ($this->locationId == "Fra20") echo '"selected="selected"'; ?>>Normandy - France</option>

<option value="Fra21" <?php if ($this->locationId == "Fra21") echo '"selected="selected"'; ?>>Paris - France</option>

<option value="Fra22" <?php if ($this->locationId == "Fra22") echo '"selected="selected"'; ?>>Strasbourg - France</option>

<option value="Fra23" <?php if ($this->locationId == "Fra23") echo '"selected="selected"'; ?>>Toulouse - France</option>

<option value="Ger11" <?php if ($this->locationId == "Ger11") echo '"selected="selected"'; ?>>Berlin - Germany</option>

<option value="Ger12" <?php if ($this->locationId == "Ger12") echo '"selected="selected"'; ?>>Bremen - Germany</option>

<option value="Ger13" <?php if ($this->locationId == "Ger13") echo '"selected="selected"'; ?>>Cologne - Germany</option>

<option value="Ger14" <?php if ($this->locationId == "Ger14") echo '"selected="selected"'; ?>>Dresden - Germany</option>

<option value="Ger15" <?php if ($this->locationId == "Ger15") echo '"selected="selected"'; ?>>Dusseldorf - Germany</option>

<option value="Ger16" <?php if ($this->locationId == "Ger16") echo '"selected="selected"'; ?>>Essen / Ruhr - Germany</option>

<option value="Ger17" <?php if ($this->locationId == "Ger17") echo '"selected="selected"'; ?>>Frankfurt - Germany</option>

<option value="Ger18" <?php if ($this->locationId == "Ger18") echo '"selected="selected"'; ?>>Hamburg - Germany</option>

<option value="Ger19" <?php if ($this->locationId == "Ger19") echo '"selected="selected"'; ?>>Hannover - Germany</option>

<option value="Ger20" <?php if ($this->locationId == "Ger20") echo '"selected="selected"'; ?>>Heidelberg - Germany</option>

<option value="Ger21" <?php if ($this->locationId == "Ger21") echo '"selected="selected"'; ?>>Leipzig - Germany</option>

<option value="Ger22" <?php if ($this->locationId == "Ger22") echo '"selected="selected"'; ?>>Munich - Germany</option>

<option value="Ger23" <?php if ($this->locationId == "Ger23") echo '"selected="selected"'; ?>>Stuttgart - Germany</option>

<option value="Ira11" <?php if ($this->locationId == "Ira11") echo '"selected="selected"'; ?>>Esfahan - Iran</option>

<option value="Ira21" <?php if ($this->locationId == "Ira21") echo '"selected="selected"'; ?>>Shiraz - Iran</option>

<option value="Ira51" <?php if ($this->locationId == "Ira51") echo '"selected="selected"'; ?>>Shomal - Iran</option>

<option value="Ira31" <?php if ($this->locationId == "Ira31") echo '"selected="selected"'; ?>>Tabriz - Iran</option>

<option value="Ira41" <?php if ($this->locationId == "Ira41") echo '"selected="selected"'; ?>>Tehran Center - Iran</option>

<option value="Ira42" <?php if ($this->locationId == "Ira42") echo '"selected="selected"'; ?>>Tehran East - Iran</option>

<option value="Ira45" <?php if ($this->locationId == "Ira45") echo '"selected="selected"'; ?>>Tehran North - Iran</option>

<option value="Ira44" <?php if ($this->locationId == "Ira44") echo '"selected="selected"'; ?>>Tehran South - Iran</option>

<option value="Ira43" <?php if ($this->locationId == "Ira43") echo '"selected="selected"'; ?>>Tehran West - Iran</option>

<option value="Jap11" <?php if ($this->locationId == "Jap11") echo '"selected="selected"'; ?>>Fukuoka - Japan</option>

<option value="Jap12" <?php if ($this->locationId == "Jap12") echo '"selected="selected"'; ?>>Hiroshima - Japan</option>

<option value="Jap13" <?php if ($this->locationId == "Jap13") echo '"selected="selected"'; ?>>Nagoya - Japan</option>

<option value="Jap14" <?php if ($this->locationId == "Jap14") echo '"selected="selected"'; ?>>Okinawa - Japan</option>

<option value="Jap15" <?php if ($this->locationId == "Jap15") echo '"selected="selected"'; ?>>Osaka-Kobe-Kyoto - Japan</option>

<option value="Jap16" <?php if ($this->locationId == "Jap16") echo '"selected="selected"'; ?>>Sapporo - Japan</option>

<option value="Jap17" <?php if ($this->locationId == "Jap17") echo '"selected="selected"'; ?>>Tokyo - Japan</option>

<option value="New11" <?php if ($this->locationId == "New11") echo '"selected="selected"'; ?>>Auckland - New Zealand</option>

<option value="New12" <?php if ($this->locationId == "New12") echo '"selected="selected"'; ?>>Bay Of Plenty - New Zealand</option>

<option value="New13" <?php if ($this->locationId == "New13") echo '"selected="selected"'; ?>>Canterbury - New Zealand</option>

<option value="New14" <?php if ($this->locationId == "New14") echo '"selected="selected"'; ?>>Central North Island - New Zealand</option>

<option value="New15" <?php if ($this->locationId == "New15") echo '"selected="selected"'; ?>>Central Otago / Lakes - New Zealand</option>

<option value="New16" <?php if ($this->locationId == "New16") echo '"selected="selected"'; ?>>Christchurch - New Zealand</option>

<option value="New17" <?php if ($this->locationId == "New17") echo '"selected="selected"'; ?>>Coromandel - New Zealand</option>

<option value="New18" <?php if ($this->locationId == "New18") echo '"selected="selected"'; ?>>Gisborne - New Zealand</option>

<option value="New19" <?php if ($this->locationId == "New19") echo '"selected="selected"'; ?>>Hawkes Bay - New Zealand</option>

<option value="New20" <?php if ($this->locationId == "New20") echo '"selected="selected"'; ?>>Manawatu / Wanganui - New Zealand</option>

<option value="New21" <?php if ($this->locationId == "New21") echo '"selected="selected"'; ?>>Marlborough - New Zealand</option>

<option value="New22" <?php if ($this->locationId == "New22") echo '"selected="selected"'; ?>>Nelson & Bays - New Zealand</option>

<option value="New23" <?php if ($this->locationId == "New23") echo '"selected="selected"'; ?>>Northland - New Zealand</option>

<option value="New24" <?php if ($this->locationId == "New24") echo '"selected="selected"'; ?>>Otago - New Zealand</option>

<option value="New25" <?php if ($this->locationId == "New25") echo '"selected="selected"'; ?>>Pacific Islands - New Zealand</option>

<option value="New26" <?php if ($this->locationId == "New26") echo '"selected="selected"'; ?>>Southland - New Zealand</option>

<option value="New27" <?php if ($this->locationId == "New27") echo '"selected="selected"'; ?>>Taranaki - New Zealand</option>

<option value="New28" <?php if ($this->locationId == "New28") echo '"selected="selected"'; ?>>Waikato - New Zealand</option>

<option value="New29" <?php if ($this->locationId == "New29") echo '"selected="selected"'; ?>>Wairarapa - New Zealand</option>

<option value="New30" <?php if ($this->locationId == "New30") echo '"selected="selected"'; ?>>Wellington - New Zealand</option>

<option value="New31" <?php if ($this->locationId == "New31") echo '"selected="selected"'; ?>>West Coast - New Zealand</option>

<option value="Aus51" <?php if ($this->locationId == "Aus51") echo '"selected="selected"'; ?>>Adelaide - SA</option>

<option value="Uae11" <?php if ($this->locationId == "Uae11") echo '"selected="selected"'; ?>>Dubai - UAE</option>

<option value="Usa51" <?php if ($this->locationId == "Usa51") echo '"selected="selected"'; ?>>Atlanta - USA</option>

<option value="Usa18" <?php if ($this->locationId == "Usa18") echo '"selected="selected"'; ?>>Austin - USA</option>

<option value="Usa91" <?php if ($this->locationId == "Usa91") echo '"selected="selected"'; ?>>Boston - USA</option>

<option value="Usa82" <?php if ($this->locationId == "Usa82") echo '"selected="selected"'; ?>>Chicago - USA</option>

<option value="Usa18" <?php if ($this->locationId == "Usa18") echo '"selected="selected"'; ?>>Dallas - USA</option>

<option value="Usa31" <?php if ($this->locationId == "Usa31") echo '"selected="selected"'; ?>>Denver - USA</option>

<option value="Usa10" <?php if ($this->locationId == "Usa10") echo '"selected="selected"'; ?>>Detroit - USA</option>

<option value="Usa61" <?php if ($this->locationId == "Usa61") echo '"selected="selected"'; ?>>Honolulu - USA</option>

<option value="Usa71" <?php if ($this->locationId == "Usa71") echo '"selected="selected"'; ?>>Houston - USA</option>

<option value="Usa13" <?php if ($this->locationId == "Usa13") echo '"selected="selected"'; ?>>Las Vegas - USA</option>

<option value="Usa21" <?php if ($this->locationId == "Usa21") echo '"selected="selected"'; ?>>Los Angeles - USA</option>

<option value="Usa41" <?php if ($this->locationId == "Usa41") echo '"selected="selected"'; ?>>Miami - USA</option>

<option value="Usa11" <?php if ($this->locationId == "Usa11") echo '"selected="selected"'; ?>>Minneapolis - USA</option>

<option value="Usa14" <?php if ($this->locationId == "Usa14") echo '"selected="selected"'; ?>>New York - USA</option>

<option value="Usa27" <?php if ($this->locationId == "Usa27") echo '"selected="selected"'; ?>>Orange County - USA</option>

<option value="Usa17" <?php if ($this->locationId == "Usa17") echo '"selected="selected"'; ?>>Philadelphia - USA</option>

<option value="Usa11" <?php if ($this->locationId == "Usa11") echo '"selected="selected"'; ?>>Phoenix - USA</option>

<option value="Usa16" <?php if ($this->locationId == "Usa16") echo '"selected="selected"'; ?>>Portland - USA</option>

<option value="Usa15" <?php if ($this->locationId == "Usa15") echo '"selected="selected"'; ?>>Raleigh - USA</option>

<option value="Usa28" <?php if ($this->locationId == "Usa28") echo '"selected="selected"'; ?>>Sacramento - USA</option>

<option value="Usa29" <?php if ($this->locationId == "Usa29") echo '"selected="selected"'; ?>>San Diego - USA</option>

<option value="Usa21" <?php if ($this->locationId == "Usa21") echo '"selected="selected"'; ?>>San Francisco Bay Area - USA</option>

<option value="Usa19" <?php if ($this->locationId == "Usa19") echo '"selected="selected"'; ?>>Seattle - USA</option>

<option value="Usa12" <?php if ($this->locationId == "Usa12") echo '"selected="selected"'; ?>>St Louis - USA</option>

<option value="Usa20" <?php if ($this->locationId == "Usa20") echo '"selected="selected"'; ?>>Washington Dc - USA</option>

