<script type="text/javascript">

$(document).ready(function() {

	//Default Action
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content

	//On Click Event
	$("ul.tabs li").click(function() {
		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content
		var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active content
		return false;
	});




});

function showPhotoTab()
{
	$("ul.tabs li").removeClass("active"); //Remove any "active" class
	var photoTab = $("ul.tabs li[tabname|=photo]");
	$(photoTab).addClass("active"); //Add "active" class to selected tab
	$(".tab_content").hide(); //Hide all tab content
	var activeTab = $(photoTab).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	$(activeTab).fadeIn(); //Fade in the active content
	return false;

}

</script>

<div class="formandresultlistwrap">
	<div class="refineformwrap">
		<?php echo $this->form->populate(Common::stdClassToArray($this->paramsHolder));?>
	</div>
	<div class="postingwrap">
		<div class="postingtitle">
			<?php echo $this->posting->getTitle()?>
		</div>
		<div class="postingdetail">
			<?php
				$detailTab = DetailTab::DetailTabFactory($this->posting);
				$detailTab->printTabs();
			?>
		</div>
	</div>
	<div class="clear"></div>
</div>