<script type="text/javascript">

$(document).ready(function() {

	//Default Action
	//$(".tab_content").hide(); //Hide all content
	//$("ul.tabs li:first").addClass("active").show(); //Activate first tab

	<?php
	 /*
		if (empty($this->tab))
		{
			echo '$("ul.tabs li:first").addClass("active").show();'; //Activate first tab
 			echo '$(".tab_content:first").show();'; //Show first tab content
		}
		else
		{
			echo 'var Tab = $("ul.tabs li[tabname|=' . $this->tab . ']");';
			echo '$(Tab).addClass("active");';
			echo 'var activeTab = $(Tab).find("a").attr("href");';
			echo '$(activeTab).show();';
		}
		*/
	?>


	//On Click Event
	$("ul.tabs li").click(function() {
		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content
		var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active content
		return false;
	});




});

function showPhotoTab()
{
	$("ul.tabs li").removeClass("active"); //Remove any "active" class
	var photoTab = $("ul.tabs li[tabname|=photo]");
	$(photoTab).addClass("active"); //Add "active" class to selected tab
	$(".tab_content").hide(); //Hide all tab content
	var activeTab = $(photoTab).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	$(activeTab).fadeIn(); //Fade in the active content
	return false;

}

</script>

<div class="formandresultlistwrap">
	<div class="refineformwrap">
		<?php echo $this->form->populate(Common::stdClassToArray($this->paramsHolder));?>
	</div>
	<div class="postingwrap">
		<div class="postingtitle">
			<?php echo $this->detailTab->getTitle()?>
		</div>
		<div class="postingdetail">
			<?php
				try{

				$this->detailTab->printTabs();
				}catch(Exception $e)
				{
					echo $e;
				}
			?>
		</div>
	</div>
	<div class="clear"></div>
</div>